version: "3"

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: "no"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: "vegnet"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: